#include "DistrhoPlugin.hpp"
#include "oracle_core.hpp"
#include <algorithm>
#include <array>
#include <cmath>
START_NAMESPACE_DISTRHO
namespace{using namespace downspout::oracle;Transport ct(const TimePosition&x){Transport t;t.valid=x.bbt.valid;t.playing=x.playing;if(t.valid){t.bar=x.bbt.bar-1;t.barBeat=x.bbt.beat-1+(x.bbt.ticksPerBeat>0?x.bbt.tick/x.bbt.ticksPerBeat:0);t.beatsPerBar=x.bbt.beatsPerBar;t.beatType=x.bbt.beatType;t.bpm=x.bbt.beatsPerMinute;}return t;}}
class OraclePlugin:public Plugin{public:OraclePlugin():Plugin(kParameterCount,0,0){for(std::uint32_t i=0;i<kParameterCount;++i)p_[i]=kParameterSpecs[i].defaultValue;}
protected:const char*getLabel()const override{return"Oracle";}const char*getDescription()const override{return"Bounded audio and MIDI listener with CC and note responses.";}const char*getMaker()const override{return"danja";}const char*getHomePage()const override{return"https://danja.github.io/downspout/";}const char*getLicense()const override{return"MIT";}std::uint32_t getVersion()const override{return d_version(0,1,0);}std::int64_t getUniqueId()const override{return d_cconst('O','r','c','l');}
void initParameter(std::uint32_t i,Parameter&q)override{auto&s=kParameterSpecs[i];q.name=s.name;q.symbol=s.symbol;q.hints=s.output?kParameterIsOutput:kParameterIsAutomatable;if(s.integer)q.hints|=kParameterIsInteger;q.ranges={s.defaultValue,s.minimum,s.maximum};}
float getParameterValue(std::uint32_t i)const override{switch(i){case kStatusLevel:return s_.level;case kStatusBrightness:return s_.brightness;case kStatusDensity:return s_.density;case kStatusPitchClass:return s_.pitchClass;case kStatusOnset:return s_.onset;case kStatusFaults:return static_cast<float>(s_.faults);default:return p_[i];}}
void setParameterValue(std::uint32_t i,float v)override{if(i<kParameterCount&&!kParameterSpecs[i].output)p_[i]=downspout::generative::clampParam(v,kParameterSpecs[i]);}
void activate()override{reset(s_);}void run(const float**in,float**out,std::uint32_t n,const MidiEvent*events,std::uint32_t count)override{for(std::uint32_t i=0;i<n;++i){out[0][i]=std::isfinite(in[0][i])?in[0][i]:0;out[1][i]=std::isfinite(in[1][i])?in[1][i]:0;}std::array<downspout::generative::MidiEvent,512>mi{};count=std::min<std::uint32_t>(count,mi.size());for(std::uint32_t i=0;i<count;++i){mi[i].frame=events[i].frame;mi[i].size=static_cast<std::uint8_t>(std::min<std::uint32_t>(events[i].size,4));auto*d=events[i].size>MidiEvent::kDataSize?events[i].dataExt:events[i].data;for(std::uint8_t b=0;b<mi[i].size;++b)mi[i].data[b]=d[b];}auto block=process(s_,p_,ct(getTimePosition()),n,getSampleRate(),in[0],in[1],mi.data(),count);for(std::uint32_t i=0;i<block.count;++i){MidiEvent e{};e.frame=block.events[i].frame;e.size=block.events[i].size;for(std::uint8_t b=0;b<e.size;++b)e.data[b]=block.events[i].data[b];writeMidiEvent(e);}}
private:std::array<float,kParameterCount>p_{};downspout::oracle::State s_{};DISTRHO_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(OraclePlugin)};Plugin*createPlugin(){return new OraclePlugin();}END_NAMESPACE_DISTRHO
