#include "orbit_core.hpp"
#include <algorithm>
#include <cmath>
namespace downspout::orbit {
namespace{float pv(const std::array<float,kParameterCount>&p,Param id){return downspout::generative::clampParam(p[id],kParameterSpecs[id]);}float walk(std::uint64_t seed,std::int64_t step){return downspout::generative::randomUnit(seed,step)*2-1;}}
void prepare(State&s,double sr){sr=std::max(8000.0,sr);const auto size=static_cast<std::size_t>(sr*0.05)+4;if(s.sampleRate==sr&&s.delayL.size()==size)return;s.sampleRate=sr;s.delayL.assign(size,0);s.delayR.assign(size,0);reset(s);}
void reset(State&s)noexcept{std::fill(s.delayL.begin(),s.delayL.end(),0);std::fill(s.delayR.begin(),s.delayR.end(),0);s.write=0;s.lowL=s.lowR=s.statusPan=s.statusDistance=0;}
void process(State&s,const std::array<float,kParameterCount>&p,const Transport&t,std::uint32_t n,double sr,const float*l,const float*r,float*ol,float*orr)noexcept{
 if(s.sampleRate!=sr||s.delayL.empty()){if(ol)std::fill_n(ol,n,0);if(orr)std::fill_n(orr,n,0);return;}const double start=t.valid?downspout::generative::absoluteQuarter(t):0,qpf=std::clamp(t.bpm,1.0,999.0)/(60.0*std::max(1.0,sr)),rate=pv(p,kRate);const int trajectory=static_cast<int>(std::lround(pv(p,kTrajectory)));const std::uint64_t seed=static_cast<std::uint64_t>(std::lround(pv(p,kSeed)));
 for(std::uint32_t i=0;i<n;++i){const double q=start+i*qpf,phase=q/rate,turn=phase-std::floor(phase);float position=0,distance=pv(p,kDistance);if(trajectory==0){position=static_cast<float>(std::sin(phase*6.283185307179586));distance=std::clamp(distance+0.25f*static_cast<float>(std::cos(phase*6.283185307179586)),0.0f,1.0f);}else if(trajectory==1)position=static_cast<float>(std::sin(phase*3.141592653589793));else if(trajectory==2){const auto step=static_cast<std::int64_t>(std::floor(phase));const float a=walk(seed,step),b=walk(seed,step+1),smooth=static_cast<float>(turn*turn*(3-2*turn));position=a+(b-a)*smooth;distance=std::clamp(distance+0.2f*walk(seed+99,step),0.0f,1.0f);}else{position=static_cast<float>(std::sin(phase*6.283185307179586));distance=std::clamp(distance+0.25f*static_cast<float>(std::sin(phase*12.566370614359172)),0.0f,1.0f);}position*=pv(p,kDepth);s.statusPan=position;s.statusDistance=distance;
  float inL=l&&std::isfinite(l[i])?l[i]:0,inR=r&&std::isfinite(r[i])?r[i]:0;const float mid=0.5f*(inL+inR),side=0.5f*(inL-inR)*pv(p,kWidth);inL=mid+side;inR=mid-side;s.delayL[s.write]=inL;s.delayR[s.write]=inR;const float delayMs=pv(p,kDoppler)*8.0f*(position+1);const auto delay=static_cast<std::uint32_t>(delayMs*0.001*sr);const auto read=(s.write+s.delayL.size()-std::min<std::size_t>(delay,s.delayL.size()-1))%s.delayL.size();float wetL=s.delayL[read],wetR=s.delayR[read];s.write=(s.write+1)%s.delayL.size();const float coefficient=0.03f+(1-distance)*0.45f;s.lowL+=coefficient*(wetL-s.lowL);s.lowR+=coefficient*(wetR-s.lowR);const float gain=1.0f-0.62f*distance;const float leftGain=std::sqrt(0.5f*(1-position)),rightGain=std::sqrt(0.5f*(1+position));wetL=s.lowL*gain*leftGain+0.12f*s.lowR*rightGain;wetR=s.lowR*gain*rightGain+0.12f*s.lowL*leftGain;const float mix=pv(p,kMix);if(ol)ol[i]=std::clamp(inL*(1-mix)+wetL*mix,-1.5f,1.5f);if(orr)orr[i]=std::clamp(inR*(1-mix)+wetR*mix,-1.5f,1.5f);}
}
} // namespace downspout::orbit
