#ifndef DOWNSPOUT_MIXGEN_DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DOWNSPOUT_MIXGEN_DISTRHO_PLUGIN_INFO_H_INCLUDED

#define DISTRHO_PLUGIN_BRAND "Downspout"
#define DISTRHO_PLUGIN_NAME "Mixgen"
#define DISTRHO_PLUGIN_URI "https://danja.github.io/downspout/plugins/mixgen"
#define DISTRHO_PLUGIN_CLAP_ID "it.hyperdata.downspout.mixgen"
#define DISTRHO_PLUGIN_BRAND_ID DnSp
#define DISTRHO_PLUGIN_UNIQUE_ID MxGn
#define DISTRHO_PLUGIN_HAS_UI 1
#define DISTRHO_PLUGIN_IS_RT_SAFE 1
#define DISTRHO_PLUGIN_NUM_INPUTS 2
#define DISTRHO_PLUGIN_NUM_OUTPUTS 2
#define DISTRHO_PLUGIN_WANT_MIDI_OUTPUT 1
#define DISTRHO_PLUGIN_WANT_TIMEPOS 1
#define DISTRHO_PLUGIN_VST3_CATEGORIES "Fx|Tools"
#define DISTRHO_UI_DEFAULT_WIDTH 1080
#define DISTRHO_UI_DEFAULT_HEIGHT 720
#define DISTRHO_UI_USE_NANOVG 1

#endif
