add_library(downspout_mnemosyne_core STATIC src/mnemosyne_core.cpp)
target_link_libraries(downspout_mnemosyne_core PUBLIC downspout-project-options)
target_include_directories(downspout_mnemosyne_core PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include" "${PROJECT_SOURCE_DIR}/plugins/generative-common/include")
if(DOWNSPOUT_ENABLE_DPF AND DOWNSPOUT_DPF_DIR)
dpf_add_plugin(mnemosyne TARGETS ${DOWNSPOUT_DPF_PLUGIN_TARGETS} ${DOWNSPOUT_DPF_PLUGIN_ARGS} FILES_DSP src/dpf/MnemosynePlugin.cpp FILES_UI src/dpf/MnemosyneUI.cpp)
target_link_libraries(mnemosyne-dsp PUBLIC downspout_mnemosyne_core)
target_link_libraries(mnemosyne-ui PUBLIC downspout_mnemosyne_core)
target_include_directories(mnemosyne PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include" "${PROJECT_SOURCE_DIR}/plugins/generative-common/include" "${CMAKE_CURRENT_SOURCE_DIR}/src/dpf")
target_include_directories(mnemosyne-ui PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include" "${PROJECT_SOURCE_DIR}/plugins/generative-common/include" "${CMAKE_CURRENT_SOURCE_DIR}/src/dpf")
install(DIRECTORY "${PROJECT_BINARY_DIR}/bin/mnemosyne.vst3" DESTINATION "." OPTIONAL)
endif()
if(BUILD_TESTING)
add_executable(downspout_mnemosyne_core_tests tests/mnemosyne_core_tests.cpp)
target_link_libraries(downspout_mnemosyne_core_tests PRIVATE downspout_mnemosyne_core)
add_test(NAME downspout_mnemosyne_core_tests COMMAND downspout_mnemosyne_core_tests)
endif()
