#ifndef DOWNSPOUT_EMIX_DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DOWNSPOUT_EMIX_DISTRHO_PLUGIN_INFO_H_INCLUDED

#define DISTRHO_PLUGIN_BRAND   "Downspout"
#define DISTRHO_PLUGIN_NAME    "E-Mix"
#define DISTRHO_PLUGIN_URI     "https://danja.github.io/downspout/plugins/e-mix"
#define DISTRHO_PLUGIN_CLAP_ID "it.hyperdata.downspout.e-mix"

#define DISTRHO_PLUGIN_BRAND_ID DnSp
#define DISTRHO_PLUGIN_UNIQUE_ID EMix

#define DISTRHO_PLUGIN_HAS_UI           1
#define DISTRHO_PLUGIN_IS_RT_SAFE       1
#define DISTRHO_PLUGIN_NUM_INPUTS       2
#define DISTRHO_PLUGIN_NUM_OUTPUTS      2
#define DISTRHO_PLUGIN_WANT_STATE       1
#define DISTRHO_PLUGIN_WANT_FULL_STATE  1
#define DISTRHO_PLUGIN_WANT_TIMEPOS     1
#define DISTRHO_PLUGIN_VST3_CATEGORIES  "Fx"
#define DISTRHO_UI_DEFAULT_WIDTH        1160
#define DISTRHO_UI_DEFAULT_HEIGHT       680
#define DISTRHO_UI_USE_NANOVG           1
#define DISTRHO_UI_FILE_BROWSER         0

#endif
