#ifndef DOWNSPOUT_DAMIANO_DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DOWNSPOUT_DAMIANO_DISTRHO_PLUGIN_INFO_H_INCLUDED

#define DISTRHO_PLUGIN_BRAND   "Downspout"
#define DISTRHO_PLUGIN_NAME    "Damiano"
#define DISTRHO_PLUGIN_URI     "https://danja.github.io/downspout/plugins/damiano"
#define DISTRHO_PLUGIN_CLAP_ID "it.hyperdata.downspout.damiano"

#define DISTRHO_PLUGIN_BRAND_ID DnSp
#define DISTRHO_PLUGIN_UNIQUE_ID Dami

#define DOWNSPOUT_PLUGIN_VERSION_MAJOR  0
#define DOWNSPOUT_PLUGIN_VERSION_MINOR  1
#define DOWNSPOUT_PLUGIN_VERSION_PATCH  0
#define DOWNSPOUT_PLUGIN_VERSION_STRING "v0.1.0"

#define DISTRHO_PLUGIN_HAS_UI           1
#define DISTRHO_PLUGIN_IS_RT_SAFE       1
#define DISTRHO_PLUGIN_NUM_INPUTS       2
#define DISTRHO_PLUGIN_NUM_OUTPUTS      2
#define DISTRHO_PLUGIN_WANT_MIDI_INPUT  1
#define DISTRHO_PLUGIN_VST3_CATEGORIES  "Fx|Distortion"
#define DISTRHO_UI_DEFAULT_WIDTH        780
#define DISTRHO_UI_DEFAULT_HEIGHT       500
#define DISTRHO_UI_USE_NANOVG           1

#endif
