#ifndef DOWNSPOUT_GUARDIAN_DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DOWNSPOUT_GUARDIAN_DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_BRAND "Downspout"
#define DISTRHO_PLUGIN_NAME "Guardian"
#define DISTRHO_PLUGIN_URI "https://danja.github.io/downspout/plugins/guardian"
#define DISTRHO_PLUGIN_CLAP_ID "it.hyperdata.downspout.guardian"
#define DISTRHO_PLUGIN_BRAND_ID DnSp
#define DISTRHO_PLUGIN_UNIQUE_ID Grdn
#define DISTRHO_PLUGIN_HAS_UI 1
#define DISTRHO_PLUGIN_IS_RT_SAFE 1
#define DISTRHO_PLUGIN_NUM_INPUTS 2
#define DISTRHO_PLUGIN_NUM_OUTPUTS 2
#define DISTRHO_PLUGIN_WANT_LATENCY 1
#define DISTRHO_PLUGIN_VST3_CATEGORIES "Fx|Mastering"
#define DISTRHO_UI_DEFAULT_WIDTH 960
#define DISTRHO_UI_DEFAULT_HEIGHT 780
#define DISTRHO_UI_USE_NANOVG 1
#endif
