#include "mosaic_core.hpp"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
namespace downspout::mosaic {
namespace{float pv(const std::array<float,kParameterCount>&p,Param id){return downspout::generative::clampParam(p[id],kParameterSpecs[id]);}int iv(const std::array<float,kParameterCount>&p,Param id){return static_cast<int>(std::lround(pv(p,id)));}
std::uint32_t u32(const unsigned char*p){return p[0]|p[1]<<8|p[2]<<16|p[3]<<24;}std::uint16_t u16(const unsigned char*p){return static_cast<std::uint16_t>(p[0]|p[1]<<8);}
void trigger(State&s,const std::array<float,kParameterCount>&p,const Pool*pool,int note,int velocity,double sr){if(!pool)return;std::array<int,kPoolSize>loaded{};int count=0;for(int i=0;i<kPoolSize;++i)if(!pool->samples[i].data.empty())loaded[count++]=i;if(count==0)return;const std::uint64_t serial=s.triggerSerial++;const int slot=loaded[downspout::generative::randomInt(iv(p,kSeed),serial,0,count-1)];const Sample&sample=pool->samples[slot];Voice*voice=nullptr;for(auto&v:s.voices)if(!v.active){voice=&v;break;}if(!voice)voice=&s.voices[serial%s.voices.size()];const std::uint32_t frames=static_cast<std::uint32_t>(sample.data.size()/std::max(1u,sample.channels));const std::uint32_t slice=std::max(1u,static_cast<std::uint32_t>(frames*pv(p,kSliceSize)));const std::uint32_t start=frames>slice?static_cast<std::uint32_t>(downspout::generative::randomUnit(iv(p,kSeed),serial+33)*(frames-slice)):0;const int range=iv(p,kPitchRange);const int transpose=range>0?downspout::generative::randomInt(iv(p,kSeed),serial+49,-range,range):note-60;voice->sample=&sample;voice->start=start;voice->end=std::min(frames,start+slice);voice->reverse=downspout::generative::randomUnit(iv(p,kSeed),serial+77)<pv(p,kReverseChance);voice->position=voice->reverse?voice->end-1:start;voice->increment=std::pow(2.0,transpose/12.0)*sample.sampleRate/std::max(1.0,sr);voice->envelope=0;voice->pan=(downspout::generative::randomUnit(iv(p,kSeed),serial+91)*2-1)*pv(p,kStereoSpread);voice->active=true;voice->releasing=false;(void)velocity;}
}
LoadResult loadWav(const std::string&path){LoadResult out;std::ifstream f(path,std::ios::binary);if(!f){out.error="open failed";return out;}std::array<unsigned char,12>h{};f.read(reinterpret_cast<char*>(h.data()),h.size());if(f.gcount()!=12||std::memcmp(h.data(),"RIFF",4)||std::memcmp(h.data()+8,"WAVE",4)){out.error="not RIFF/WAVE";return out;}std::uint16_t format=0,channels=0,bits=0;std::uint32_t rate=0;std::vector<unsigned char>bytes;while(f){std::array<unsigned char,8>ch{};f.read(reinterpret_cast<char*>(ch.data()),8);if(f.gcount()!=8)break;const std::uint32_t size=u32(ch.data()+4);std::vector<unsigned char>data(size);f.read(reinterpret_cast<char*>(data.data()),size);if(std::memcmp(ch.data(),"fmt ",4)==0&&size>=16){format=u16(data.data());channels=u16(data.data()+2);rate=u32(data.data()+4);bits=u16(data.data()+14);}else if(std::memcmp(ch.data(),"data",4)==0)bytes=std::move(data);if(size&1)f.get();}
if((format!=1&&format!=3)||channels<1||channels>2||rate<8000||rate>384000||(bits!=16&&!(format==3&&bits==32))||bytes.empty()){out.error="unsupported WAV";return out;}const std::uint32_t bps=bits/8,frames=bytes.size()/(bps*channels);if(frames>rate*60u){out.error="sample exceeds 60 seconds";return out;}out.sample.channels=channels;out.sample.sampleRate=rate;out.sample.data.resize(static_cast<std::size_t>(frames)*channels);for(std::uint32_t i=0;i<frames*channels;++i){if(format==1){const auto raw=static_cast<std::int16_t>(u16(bytes.data()+i*2));out.sample.data[i]=raw/32768.0f;}else{float v;std::memcpy(&v,bytes.data()+i*4,4);out.sample.data[i]=std::isfinite(v)?std::clamp(v,-1.0f,1.0f):0;}}return out;}
void reset(State&s)noexcept{s={};}
void process(State&s,const std::array<float,kParameterCount>&p,const Transport&t,std::uint32_t n,double sr,const Pool*pool,const MidiEvent*events,std::uint32_t count,float*l,float*r)noexcept{
 if(l)std::fill_n(l,n,0);if(r)std::fill_n(r,n,0);s.statusLoaded=0;if(pool)for(const auto&sample:pool->samples)if(!sample.data.empty())++s.statusLoaded;s.statusMissing=s.statusLoaded==0;
 const int mode=iv(p,kMode);if((mode==1||mode==2)&&t.valid&&t.playing){const double start=downspout::generative::absoluteQuarter(t),qpf=std::clamp(t.bpm,1.0,999.0)/(60.0*std::max(1.0,sr));const std::int64_t step=static_cast<std::int64_t>(std::floor((start+1e-8)/0.25));if(step!=s.lastAutoStep){s.lastAutoStep=step;if(downspout::generative::randomUnit(iv(p,kSeed),step)<pv(p,kDensity))trigger(s,p,pool,60,96,sr);}}
 for(std::uint32_t e=0;e<count;++e)if((mode==0||mode==2)&&events[e].size>=3&&(events[e].data[0]&0xf0)==0x90&&events[e].data[2]>0)trigger(s,p,pool,events[e].data[1],events[e].data[2],sr);
 s.statusVoices=0;for(auto&v:s.voices){if(!v.active||!v.sample)continue;++s.statusVoices;const auto&sample=*v.sample;const std::uint32_t frames=sample.data.size()/sample.channels;for(std::uint32_t i=0;i<n&&v.active;++i){const auto index=static_cast<std::uint32_t>(std::clamp(v.position,0.0,static_cast<double>(frames-1)));const float a=sample.data[index*sample.channels],b=sample.channels>1?sample.data[index*sample.channels+1]:a;const float attackStep=1.0f/std::max(1.0,pv(p,kAttack)*sr),releaseStep=1.0f/std::max(1.0,pv(p,kRelease)*sr);if(!v.releasing)v.envelope=std::min(1.0f,v.envelope+attackStep);else v.envelope=std::max(0.0f,v.envelope-releaseStep);const float gl=std::sqrt(0.5f*(1-v.pan)),gr=std::sqrt(0.5f*(1+v.pan));if(l)l[i]+=a*v.envelope*gl*0.45f;if(r)r[i]+=b*v.envelope*gr*0.45f;v.position+=v.reverse?-v.increment:v.increment;if(v.position<v.start||v.position>=v.end)v.releasing=true;if(v.envelope<=0&&v.releasing)v.active=false;}}
 for(std::uint32_t i=0;i<n;++i){if(l)l[i]=std::tanh(l[i]);if(r)r[i]=std::tanh(r[i]);}
}
} // namespace downspout::mosaic
