#include "guardian_core.hpp"
#include <algorithm>
#include <cmath>
namespace downspout::guardian {
namespace{float pv(const std::array<float,kParameterCount>&p,Param id){return downspout::generative::clampParam(p[id],kParameterSpecs[id]);}float db(float value){return std::pow(10.0f,value/20.0f);}float hp(float x,float&px,float&py,double sr){const float r=static_cast<float>(std::exp(-6.283185307179586*8.0/std::max(1.0,sr)));const float y=x-px+r*py;px=x;py=std::isfinite(y)?y:0;return py;}}
void prepare(State&s,double sr){sr=std::max(8000.0,sr);const auto size=static_cast<std::size_t>(std::ceil(sr*0.021))+4;if(s.sampleRate==sr&&s.delayL.size()==size)return;s.sampleRate=sr;s.delayL.assign(size,0);s.delayR.assign(size,0);resetAudio(s);}
void resetAudio(State&s)noexcept{std::fill(s.delayL.begin(),s.delayL.end(),0);std::fill(s.delayR.begin(),s.delayR.end(),0);s.write=0;s.gain=1;s.dcXL=s.dcYL=s.dcXR=s.dcYR=s.previousL=s.previousR=0;s.peak=0;s.reductionDb=0;s.silence=true;}
std::uint32_t lookaheadFrames(const std::array<float,kParameterCount>&p,double sr)noexcept{return static_cast<std::uint32_t>(std::lround(pv(p,kLookaheadMs)*0.001*std::max(1.0,sr)));}
void process(State&s,const std::array<float,kParameterCount>&p,std::uint32_t n,double sr,const float*l,const float*r,float*ol,float*orr)noexcept{
 if(s.sampleRate!=sr||s.delayL.empty()){if(ol)std::fill_n(ol,n,0);if(orr)std::fill_n(orr,n,0);return;}const int reset=static_cast<int>(std::lround(pv(p,kReset)));if(reset!=s.resetSerial){s.resetSerial=reset;s.faults=0;s.overload=false;resetAudio(s);}const float ceiling=db(pv(p,kCeilingDb)),release=1.0f-std::exp(-1.0f/static_cast<float>(sr*pv(p,kReleaseMs)*0.001));const auto latency=std::min<std::size_t>(lookaheadFrames(p,sr),s.delayL.size()-1);double energy=0;s.peak=0;float minimumGain=1;
 for(std::uint32_t i=0;i<n;++i){float a=l?l[i]:0,b=r?r[i]:0;if(!std::isfinite(a)){a=0;++s.faults;}if(!std::isfinite(b)){b=0;++s.faults;}if(pv(p,kDcRemove)>0.5f){a=hp(a,s.dcXL,s.dcYL,sr);b=hp(b,s.dcXR,s.dcYR,sr);}s.delayL[s.write]=a;s.delayR[s.write]=b;float detected=std::max(std::fabs(a),std::fabs(b));if(pv(p,kTruePeak)>0.5f)detected=std::max(detected,std::max(std::fabs(a)+0.25f*std::fabs(a-s.previousL),std::fabs(b)+0.25f*std::fabs(b-s.previousR)));s.previousL=a;s.previousR=b;s.peak=std::max(s.peak,detected);const float target=detected>ceiling?ceiling/std::max(1e-12f,detected):1.0f;if(target<s.gain)s.gain=target;else s.gain+=release*(target-s.gain);minimumGain=std::min(minimumGain,s.gain);const auto read=(s.write+s.delayL.size()-latency)%s.delayL.size();float x=s.delayL[read]*s.gain,y=s.delayR[read]*s.gain;s.write=(s.write+1)%s.delayL.size();if(pv(p,kSoftClip)>0.5f){const float norm=std::tanh(1.5f);x=std::tanh(x*1.5f)/norm;y=std::tanh(y*1.5f)/norm;}if(!std::isfinite(x)){x=0;++s.faults;}if(!std::isfinite(y)){y=0;++s.faults;}x=std::clamp(x,-ceiling,ceiling);y=std::clamp(y,-ceiling,ceiling);if(ol)ol[i]=x;if(orr)orr[i]=y;energy+=x*x+y*y;if(detected>1.0f)s.overload=true;}
 s.reductionDb=-20.0f*std::log10(std::max(1e-6f,minimumGain));const float rms=n?static_cast<float>(std::sqrt(energy/(2*n))):0;s.silence=rms<db(pv(p,kSilenceDb));
}
} // namespace downspout::guardian
